template_path: remote-templates/vpc.yaml
stack_name: computevpc
parameters:
  VpcSubnetPrefix: "10.5"
  VpcName: computevpc
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/vpc.yaml --create-dirs -o remote-templates/vpc.yaml"
