template_path: remote-templates/essentials.yaml
stack_name: essentials
parameters:
  FhcrcVpnCidrip: {{ environment_variable.FhcrcVpnCidrip }}
  OperatorEmail: aws.scicomp@sagebase.org
  VpcPeeringRequesterAwsAccountId: "{{ environment_variable.AdmincentralAwsAccountId }}"
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AwsInfraCfBucket }}/aws-infra/master/essentials.yml ./remote-templates/essentials.yaml"
