template_path: templates/SynapseExternalBucket.yaml
stack_name: GatesKI-DiabetesStudy
parameters:
  AllowWriteBucket: "true"
  SynapseUserName: "khai"
hooks:
  after_create:
    - !cmd "auto-provision/SynapseExternalBucketHelper.sh GatesKI-DiabetesStudy"
