template_path: "jumpcloud-idp.yaml"
stack_name: "jumpcloud-idp"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  ScicompAdminMetadata: !file_contents idp/jumpcloud/scicomp-admin.xml
  ScicompDeveloperMetadata: !file_contents idp/jumpcloud/scicomp-developer.xml
dependencies:
  - "prod/cfn-cr-saml-provider.yaml"
