template_path: remote-templates/peer-route-config.yaml
stack_name: peer-vpn-computevpc
parameters:
  PeeringConnectionId: pcx-e6cd3b8e
  VpcPrivateRouteTable: rtb-5f73c623
  VpcPublicRouteTable: rtb-6e7fca12
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://bootstrap-awss3cloudformationbucket-19qromfd235z9/aws-infra/master/peer-route-config.yml ./remote-templates/peer-route-config.yaml"
