template_path: remote/peer-route-config.yaml
stack_name: peer-vpn-computevpc
parameters:
  PeeringConnectionId: pcx-7e3bec16
  VpcPrivateRouteTable: rtb-5f73c623
  VpcPublicRouteTable: rtb-6e7fca12
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/peer-route-config.yaml --create-dirs -o templates/remote/peer-route-config.yaml"
