template_path: remote-templates/rotate-credentials.yaml
stack_name: rotate-credentials
dependencies:
  - AccountAlertTopics
parameters:
  GracePeriod: "14"
  DisableKeys: "true"
  SendEmail: "true"
  SenderEmail: "it@sagebase.org"
  SendReport: "true"
  MaxAccessKeyAge: "180"
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/bootstrap-awss3cloudformationbucket-19qromfd235z9/aws-infra/master/rotate-credentials.yaml --create-dirs -o remote-templates/rotate-credentials.yaml"
