template_path: remote-templates/RotateCredentials.yaml
stack_name: RotateCredentials
dependencies:
  - AccountAlertTopics
parameters:
  LambdaBucket: essentials-awss3lambdaartifactsbucket-x29ftznj6pqw
  GracePeriod: "14"
  DisableKeys: "true"
  SendEmail: "true"
  SenderEmail: it@sagebase.org
  SendReport: "true"
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/bootstrap-awss3cloudformationbucket-19qromfd235z9/aws-infra/master/RotateCredentials.yaml --create-dirs -o remote-templates/RotateCredentials.yaml"
