# Provision an EC2 instance
template_path: templates/managed-ec2.yaml
stack_name: test-ki-rally-manager-ec2
dependencies:
  - peer-vpn-computevpc
parameters:
  # The Sage deparment for this resource
  Department: "Systems Biology"
  # The Sage project this resource will be used for
  Project: "Gates HBGDki"
  # The resource owner
  OwnerEmail: "kenneth.daily@sagebase.org"
  # EC2 instance type (available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t2.micro"
  # Name of an existing VPC subnet to run the instance in
  VpcSubnet: "PublicSubnet"
  # Name of an existing EC2 KeyPair to enable SSH access to the instance
  KeyName: test-ki-rally-manager"

   # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !notify_ec2
