template_path: remote-templates/vpc.yaml
stack_name: computevpc
parameters:
  VpcSubnetPrefix: "10.5"
  VpcName: computevpc
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AwsInfraCfBucket }}/aws-infra/master/vpc.yml ./remote-templates/vpc.yaml"
